TestNetCORE/Models/ToDoItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TestNetCORE.Models
{
    public class ToDoItem
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public bool IsChecked { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "Title is required")]
        public string Title { get; set; }
        [Required]
        [StringLength(500, ErrorMessage = "Description is required")]
        public string Description { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        public DateTime StartDateTime { get; set; }
        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        public DateTime EndDateTime { get; set; }
        public DateTime? CompletedDateTime { get; set; }
        public DateTime LastTimeModified { get; set; }
    }
}

TestNetCORE/ViewModels/ToDoItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using ToDoItem = TestNetCORE.Models.ToDoItem;

namespace TestNetCORE.ViewModels
{
    public class ToDoItemViewModel
    {
        public string Title { get; set; }
        public List<ToDoItem> Tasks { get; set; }
    }
}

TestNetCORE/Controllers/ToDoItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TestNetCORE.Models;
using TestNetCORE.ViewModels;
using ToDoItem = TestNetCORE.Models.ToDoItem;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace TestNetCORE.Controllers
{
    [Authorize]
    public class ToDoItemController : Controller
    {
        private readonly IToDoItemRepository _taskRepository;

        public ToDoItemController(IToDoItemRepository taskRepository)
        {
            _taskRepository = taskRepository;
        }
        // GET: /<controller>/
        
        public IActionResult Index()
        {
            var tasks = _taskRepository.GetAllTasks(User.FindFirstValue(ClaimTypes.NameIdentifier)).OrderBy(t => t.StartDateTime);
      

            var toDoItemViewModel = new ToDoItemViewModel()
            {
                Title = "Here is the list of your tasks",
                Tasks = tasks.ToList()
            };

            return View(toDoItemViewModel);
        }

        public IActionResult AddToDoItem()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddToDoItem(ToDoItem task)
        {
            if (ModelState.IsValid)
            {
                task.UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                _taskRepository.AddTask(task);

                return RedirectToAction("TaskAdded");
            }

            return View(task);
        }

        public IActionResult ToDoItemComplete(int id)
        {
            var task = _taskRepository.GeTaskById(id);
            if (task == null) return NotFound();

            task.CompletedDateTime = DateTime.UtcNow;
            _taskRepository.UpdateTask(task);

            return View(task);
        }

        [HttpPost]
        public IActionResult ToDoItemCheck(int id, bool checkState)
        {
            var task = _taskRepository.GeTaskById(id);
            if (task == null) return NotFound();

            task.IsChecked = checkState;

            return RedirectToAction("Index");
        }

        public IActionResult ToDoItemDetails(int id)
        {
            var task = _taskRepository.GeTaskById(id);
            if (task == null) return NotFound();

            return View(task);
        }


        public IActionResult TaskAdded()
        {
            return View();
        }

    }
}

TestNetCORE/Views/ToDoItem/AddToDoItem.cshtml
@model TestNetCORE.Models.ToDoItem

<form asp-action="AddToDoItem" method="post" class="form-horizontal" role="form">

    <div asp-validation-summary="All" class="text-danger"></div>


    @*Title*@
    <div class="form-group">
        <label style="color: white" asp-for="Title" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
    </div>

    @*Description*@
    <div class="form-group">
        <label style="color: white" asp-for="Description" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>

    @*StartDateTime*@
    <div class="form-group">
        <label style="color: white" asp-for="StartDateTime" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="StartDateTime" class="form-control" />
            <span asp-validation-for="StartDateTime" class="text-danger"></span>
        </div>
    </div>

    @*EndDateTime*@
    <div class="form-group">
        <label style="color: white" asp-for="EndDateTime" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="EndDateTime" class="form-control" />
            <span asp-validation-for="EndDateTime" class="text-danger"></span>
        </div>
    </div>

    @*Submit*@
    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Add Task" />
        </div>
    </div>

</form>

TestNetCORE/Views/ToDoItem/Index.cshtml
@using System.Security.Claims
@using Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal
@model ToDoItemViewModel

<h2 style="color: white">@Model.Title</h2>

<table class="table" style="color: white">
    <thead>
    <tr>
        <td>&#x2714;</td>
        <td>Complete</td>
        <td>Title</td>
        <td>Description</td>
        <td>Due</td>
        <td>Last Time Updated</td>
    </tr>
    </thead>
@foreach (var task in Model.Tasks)
{
    if (task.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier))
    {
        if (task.CompletedDateTime == null || task.CompletedDateTime == DateTime.MinValue)
        {
            <tr>
                <td>
                    <form asp-action="ToDoItemCheck" method="POST">
                        <input data-val="true"
                               id="isItemChecked"
                               name="isItemChecked"
                               type="checkbox"
                               value="true"/>
                        <input name="isItemChecked" type="hidden" value="false"/>
                    </form>
                </td>
                <td>
                    <a asp-controller="ToDoItem" asp-action="ToDoItemComplete" asp-route-id="@task.Id">Complete</a>
                </td>
                <td>@task.Title</td>
                <td>@task.Description</td>
                <td>@task.EndDateTime</td>
                <td>@task.LastTimeModified</td>
            </tr>
        }
    }
}
</table>

TestNetCORE/Views/ToDoItem/TaskAdded.cshtml
<h2 style="color: white">Your task has been added successfully!</h2>

TestNetCORE/Views/ToDoItem/ToDoItemComplete.cshtml
@model TestNetCORE.Models.ToDoItem

<h2 style="color: white">@Model.Title has been completed. Well done, keep up the good work!</h2>

TestNetCORE/Views/ToDoItem/ToDoItemDetails.cshtml
@model TestNetCORE.Models.ToDoItem

<h2 style="color: white">@Model.Title</h2>

<div class="thumbnail">
    <h5></h5>
    <h3>@Model.Description</h3>
    <h3></h3>
    <h4>Task Ends: @Model.EndDateTime</h4>
</div>